export const pkg = state => state.pkg
export const app = state => state.app
export const device = state => state.app.device
export const effect = state => state.app.effect
export const authEnabled = state => true
export const loading = state => state.loading
export const working = state => state.working
export const endpoints = state => state.endpoints
export const endpointsLoaded = state => state.endpointsLoaded
export const sessionId = state => state.app.sessionId
export const datacenter = state => state.app.datacenter
